[workspace]

members = [
    "pallet-tfgrid",
    "pallet-smart-contract",
    "pallet-vesting-validator",
    "pallet-burning",
    "pallet-kvstore",
    "pallet-runtime-upgrade",
    "substrate-validator-set"
]
